name: Check Release Docker Images

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, arm64]
    uses: ./.github/workflows/docker-build.yml
    with:
      build_profile: release
      architecture: ${{ matrix.architecture }}
